# Generated by Django 2.1.4 on 2018-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='usable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rightanswer',
            name='usable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wronganswer',
            name='usable',
            field=models.BooleanField(default=True),
        ),
    ]
