# Generated by Django 2.1.5 on 2019-01-20 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_auto_20190106_0310'),
        ('quizmaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOnQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.Card')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizmaker.Quiz')),
            ],
        ),
    ]
